name: Frontend CI/CD

on:
  push:
    branches: [ main ]
   

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install & Test
        run: |
          npm ci
          npm test || echo "Tests not yet implemented"

      - name: Build Application
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ vars.ECR_FRONTEND_REPO }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Update K8s Manifest
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          K8S_REPO: ${{ vars.K8S_REPO_URL }}
          IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_FRONTEND_REPO }}:${{ github.sha }}
        run: |
          git clone https://$GH_TOKEN@${K8S_REPO#https://} k8s-config
          cd k8s-config

          sed -i "s|image: .*|image: $IMAGE|" frontend-deployment.yaml

          git config user.name "Stanleyoluebube"
          git config user.email "stanleyoluebube171@gmail.com"

          git add frontend-deployment.yaml

          git commit -m "deploy: update frontend image to ${{ github.sha }}" || echo "No changes to commit"
          git push origin main